### ISSUE TITLE
Update pip version

### ISSUE THREAD

**Issue by hanruisong00** [ENSTA-U2IS/torch-uncertainty#22]
Hello, thank you for your open source code to my research has a great inspiration and help. One small question I have is that PackedLinear and PackedConv2d in packed_layers.py don't seem to correspond to the latest github repository and the folders associated with them don't seem to be updated after pip installation. For example, the PackedLinear function in the source code of pip installation has no alpha parameter. Could you please update it to facilitate the use of pip installation？

**Comment by o-laurent** [comment]
Hi! Thanks a lot for your motivating comment! 
We can update the current pip package from 0.1 to 0.1.1 to level it with the main branch if you like. Remember that our pip package is in beta and that the library will be pretty unstable in the following months (but packed layers should not change too much). This is why we make our latest changes to the _dev_ branch, which are then merged into _main_ that we aim to publish on PyPI (pip) occasionally. If you want to stay up-to-date or even contribute, you may prefer [installing the package from the source code](https://torch-uncertainty.github.io/installation.html).
Don't hesitate to let us know if you have any questions.

**Comment by o-laurent** [comment]
I am closing the issue now that the package has been published.
