### ISSUE TITLE
:wrench: Fix codecov upload in forked PRs

### ISSUE THREAD

**Issue by o-laurent** [ENSTA-U2IS/torch-uncertainty#58]
The token is not valid, and we cannot upload the coverage cf. [this GitHub action](https://github.com/ENSTA-U2IS/torch-uncertainty/actions/runs/6624353426/job/1799315236).

**Comment by o-laurent** [comment]
As Quentin's branch is also called main, it modified the coverage of origin/main branch

**Comment by qbouniot** [comment]
Unfortunately, changing the branch name from which the PR comes from did not update the coverage of origin/main branch ...

**Comment by o-laurent** [comment]
> Unfortunately, changing the branch name from which the PR comes from did not update the coverage of origin/main branch ...

We have to push on main to change it, but pushing on your PR won't change the cov. again.
