### ISSUE TITLE
:bug: issue concerning the interaction of MC-Dropout and the other methods

### ISSUE THREAD

**Issue by haofanwang** [ENSTA-U2IS/torch-uncertainty#72]
I'm running following command on cifar10

```
python3 resnet.py --version mimo --arch 18 --accelerator gpu --device 1 --benchmark True --max_epochs 75 --precision 16 --root "./data/" --num_estimators 4
```

but it raises error `RuntimeError: The size of tensor a (512) must match the size of tensor b (128) at non-singleton dimension 0`. I dive into the code and find that it may be related to [this line](https://github.com/ENSTA-U2IS/torch-uncertainty/blob/0ca696613fea034afd05f3964cd86b8d524180b7/torch_uncertainty/models/resnet/mimo.py#L42), should we remove it? @o-laurent Could you help with this?

Edit by maintainer:
- Either add an "mc_dropout" parameter to the CLI or to the models (we could have dropout during training + MIMO or else, especially for wideresnets)

**Comment by o-laurent** [comment]
Hi!
Thanks a lot for the head-up! I've just issued a temporary fix on `dev`. To access it, just `git checkout dev`. I'll update your comment to explain what happens (interaction with dropout) that we will have to solve before merging #70.
Please do not hesitate if you have any other trouble or questions!

**Comment by haofanwang** [comment]
It really helps, thanks for your quick reply.
